import { Meal } from "../../types/meal";
import SearchIcon from "./searchIcon.svg?react";
import SelectButton from "./selectButton.svg?react";
import EllipseButton from "./ellipseButton.svg?react";
import Dash from "./dash.svg?react";
import MealComponent from "./mealComponent.svg?react";
import NextButton from "./nextButton.svg?react";
import ScheduleEllipse from "./scheduleEllipse.svg?react";
import Alarm from "./alarm.svg?react";
import MealComponentEmpty from "./mealComponentEmpty.svg?react";

export { SearchIcon };
export { SelectButton };
export { EllipseButton };
export { Dash };
export { MealComponent };
export { NextButton };
export { ScheduleEllipse };
export { Alarm };
export { MealComponentEmpty };
